version = 1
enableSodiumMenu = true
dontCull = []
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "FAST"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
diagonalwalls = true
mcwdoors = true
farmersdelight = true
cratedelight = true
mcwroofs = true
enchanted-vertical-slabs = true
mcwbridges = true
mcwholidays = true
placeable_food = true
additional_lights = true
storagedelight = true
easymagic = true
mcwstairs = true
diagonalfences = true
kafvalentine = true
minecraft = true
